In [1]:
import pandas as pd
import numpy as np
from geopy.distance import geodesic
from geopy.geocoders import Nominatim
import time
geolocator = Nominatim(user_agent="OLABikes")

In [2]:
!ls

1. Data Cleaning (Basic).ipynb
2. Data Analysis and Cleaning (Advance).ipynb
3. Data Prep.ipynb
4. Model_Training.ipynb
data_analysis_ride_request.html

#### Reading Data from previous checkpoint

In [3]:
df = pd.read_csv('../Data/data_checkpoint/preprocessed_1.csv', compression = 'gzip')

## Data Cleaning with Business Understanding

### There can be cases when a user requests a ride, and their booking request is logged in our database but this user re-books his/her ride due to longer wait hours or driver refused booking or user by mistake added wrong pickup or drop locations. 

<hr>

### `Handle Case1 Rebooking Again to Same Location`: Keep only one request of same user to same pickup latitude longitude in 1hour time frame of first ride request.

<hr>

### `Handle Case2 Location entry mistake`: Keep only last request of user within 8mintues of first booking request.
#### A person booking a ride would generally book a ride that would take 8mins of bike ride time. 
#### Also, Calculate distance b/w pickup and drop. Based on distance and request time different remove bad data entries.

#### `Handle Case2.1`: Pick Up and Drop Lat-Long Distance less than 50meters = 0.05 kms; No user would like to ride for just 50meters trip. 

<hr>

### `Handle Case3`: Booking Location Outside operation zone of OLABikes
#### Check lat-long bounding box coordinates

In [4]:
df['ts'] = pd.to_datetime(df['ts'])
df.sort_values(by = ['number','ts'], inplace = True)
df.reset_index(inplace = True)

In [5]:
# you need convert first to numpy array by values and cast to int64 - output is in ns, so need divide by 10 ** 9

df['booking_timestamp'] = df.ts.values.astype(np.int64)// 10 ** 9

In [6]:
df.head(50)

,index,ts,number,pick_lat,pick_lng,drop_lat,drop_lng,hour,mins,day,month,year,dayofweek,booking_timestamp
0,2374378,2020-10-10 07:34:16,-1,12.975773,77.571070,12.878468,77.445330,7,34,10,10,2020,5,1602315256
1,2405894,2020-10-11 08:23:42,-1,12.930813,77.609530,12.960320,77.587210,8,23,11,10,2020,6,1602404622
2,2405895,2020-10-11 08:23:50,-1,12.930813,77.609530,12.960320,77.587210,8,23,11,10,2020,6,1602404630
3,2405896,2020-10-11 08:23:51,-1,12.930813,77.609530,12.960320,77.587210,8,23,11,10,2020,6,1602404631
4,2405897,2020-10-11 08:23:54,-1,12.930813,77.609530,12.960320,77.587210,8,23,11,10,2020,6,1602404634
5,2405898,2020-10-11 08:23:56,-1,12.930813,77.609530,12.960320,77.587210,8,23,11,10,2020,6,1602404636
6,2406076,2020-10-11 11:57:17,-1,12.960213,77.587460,12.930824,77.609610,11,57,11,10,2020,6,1602417437
7,2406077,2020-10-11 11:57:31,-1,12.960213,77.587460,12.930824,77.609610,11,57,11,10,2020,6,1602417451
8,2500477,2020-10-16 17:51:07,-1,12.924353,77.549410,12.932216,77.581825,17,51,16,10,2020,4,1602870667
9,2500478,2020-10-16 17:51:25,-1,12.924353,77.549410,12.932216,77.581825,17,51,16,10,2020,4,1602870685
10,2694503,2020-10-30 09:00:44,-1,12.945731,77.622500,12.973030,77.616840,9,0,30,10,2020,4,1604048444
11,3358326,2020-11-27 20:16:20,-1,13.031985,77.571280,12.960211,77.646910,20,16,27,11,2020,4,1606508180
12,3358336,2020-11-27 20:35:09,-1,13.031940,77.571260,12.960211,77.646910,20,35,27,11,2020,4,1606509309
13,3358337,2020-11-27 20:35:48,-1,13.032073,77.571290,12.960211,77.646910,20,35,27,11,2020,4,1606509348
14,3358339,2020-11-27 20:35:51,-1,13.032073,77.571290,12.960211,77.646910,20,35,27,11,2020,4,1606509351
15,3565362,2020-12-05 22:09:55,-1,12.938531,77.578940,12.952660,77.568825,22,9,5,12,2020,5,1607206195
16,3580957,2020-12-06 10:25:54,-1,12.933546,77.692894,12.977833,77.646830,10,25,6,12,2020,6,1607250354
17,3580973,2020-12-06 10:34:20,-1,12.933337,77.691180,12.977833,77.646830,10,34,6,12,2020,6,1607250860
18,3592959,2020-12-06 22:18:23,-1,12.938314,77.578830,12.952660,77.568825,22,18,6,12,2020,6,1607293103
19,3592961,2020-12-06 22:19:39,-1,12.938314,77.578830,12.952660,77.568825,22,19,6,12,2020,6,1607293179
20,3592963,2020-12-06 22:23:17,-1,12.938503,77.578860,12.952660,77.568825,22,23,6,12,2020,6,1607293397
21,3592964,2020-12-06 22:23:41,-1,12.938503,77.578860,12.952660,77.568825,22,23,6,12,2020,6,1607293421
22,3641277,2020-12-08 09:01:57,-1,12.952168,77.569050,12.909234,77.567040,9,1,8,12,2020,1,1607418117
23,3795100,2020-12-17 17:40:20,-1,12.979331,77.577910,12.944552,77.596510,17,40,17,12,2020,3,1608226820
24,3795170,2020-12-17 18:45:11,-1,12.944604,77.596620,12.979256,77.578384,18,45,17,12,2020,3,1608230711
25,3795175,2020-12-17 18:52:49,-1,12.944983,77.596800,12.979256,77.578384,18,52,17,12,2020,3,1608231169
26,3795178,2020-12-17 18:56:06,-1,12.944510,77.597130,12.979256,77.578384,18,56,17,12,2020,3,1608231366
27,3807424,2020-12-19 21:26:16,-1,12.919730,77.603030,12.950794,77.606670,21,26,19,12,2020,5,1608413176
28,3849540,2020-12-21 16:59:55,-1,12.940567,77.587395,12.981304,77.601510,16,59,21,12,2020,0,1608569995
29,3951066,2020-12-26 16:28:54,-1,12.981304,77.601510,12.999338,77.620050,16,28,26,12,2020,5,1609000134
30,3951069,2020-12-26 16:30:07,-1,12.981427,77.601420,12.999338,77.620050,16,30,26,12,2020,5,1609000207
31,3951070,2020-12-26 16:30:12,-1,12.981427,77.601420,12.999338,77.620050,16,30,26,12,2020,5,1609000212
32,4188621,2021-01-02 07:37:39,-1,12.899870,77.575590,12.953981,77.592255,7,37,2,1,2021,5,1609573059
33,4196749,2021-01-02 20:25:24,-1,12.971963,77.593960,12.913632,77.585600,20,25,2,1,2021,5,1609619124
34,4196903,2021-01-02 23:33:50,-1,12.913759,77.585520,12.952300,77.567215,23,33,2,1,2021,5,1609630430
35,4212326,2021-01-03 17:13:31,-1,12.899760,77.575590,12.923305,77.553345,17,13,3,1,2021,6,1609694011
36,4253585,2021-01-04 16:36:42,-1,12.982410,77.624620,12.933859,77.607350,16,36,4,1,2021,0,1609778202
37,4253586,2021-01-04 16:36:59,-1,12.982410,77.624620,12.933859,77.607350,16,36,4,1,2021,0,1609778219
38,4253587,2021-01-04 16:37:06,-1,12.982410,77.624620,12.933859,77.607350,16,37,4,1,2021,0,1609778226
39,4229254,2021-01-04 17:31:23,-1,12.965632,77.602880,12.950794,77.606670,17,31,4,1,2021,0,1609781483
40,4229285,2021-01-04 17:51:09,-1,12.965618,77.602790,12.981304,77.601510,17,51,4,1,2021,0,1609782669
41,4229551,2021-01-04 20:02:19,-1,12.981511,77.601390,12.940261,77.587730,20,2,4,1,2021,0,1609790539
42,4229554,2021-01-04 20:04:06,-1,12.981453,77.601360,12.940261,77.587730,20,4,4,1,2021,0,1609790646
43,4229556,2021-01-04 20:04:12,-1,12.981453,77.601360,12.940261,77.587730,20,4,4,1,2021,0,1609790652
44,4229557,2021-01-04 20:04:17,-1,12.981453,77.601360,12.940261,77.587730,20,4,4,1,2021,0,1609790657
45,4229559,2021-01-04 20:04:56,-1,12.981453,77.601360,12.940261,77.587730,20,4,4,1,2021,0,1609790696
46,4289433,2021-01-05 08:48:17,-1,12.933873,77.607346,12.994055,77.661130,8,48,5,1,2021,1,1609836497
47,4349159,2021-01-07 15:44:25,-1,12.933850,77.607376,12.852608,77.656950,15,44,7,1,2021,3,1610034265
48,4358506,2021-01-08 13:43:05,-1,12.940665,77.587280,12.966620,77.608660,13,43,8,1,2021,4,1610113385
49,4380739,2021-01-09 10:55:48,-1,12.945139,77.575130,12.967576,77.579200,10,55,9,1,2021,5,1610189748

In [7]:
df['shift_booking_ts'] = df.groupby('number')['booking_timestamp'].shift(1)
df['shift_booking_ts'].fillna(0, inplace = True)

In [8]:
df['shift_booking_ts'] = df['shift_booking_ts'].astype('int64')

In [9]:
df['booking_time_diff_hr'] = round((df['booking_timestamp'] - df['shift_booking_ts'])//3600)
df['booking_time_diff_min'] = round((df['booking_timestamp'] - df['shift_booking_ts'])//60)

In [10]:
##Booking time different in mins
df['booking_time_diff_min'].value_counts().to_dict()

{0: 2801749,
 1: 799993,
 2: 307831,
 3: 167954,
 4: 109141,
 5: 77918,
 6: 60416,
 7: 48342,
 8: 40404,
 9: 34407,
 10: 29977,
 11: 26091,
 12: 23336,
 13: 20839,
 14: 18945,
 15: 16872,
 16: 15467,
 17: 13885,
 18: 12804,
 19: 11870,
 20: 10869,
 21: 10105,
 22: 9397,
 23: 8810,
 24: 8185,
 25: 7752,
 26: 7255,
 27: 6898,
 28: 6610,
 29: 6263,
 30: 6034,
 31: 5773,
 1439: 5725,
 1440: 5712,
 32: 5702,
 1438: 5489,
 1437: 5402,
 1441: 5391,
 33: 5349,
 1442: 5303,
 1443: 5178,
 34: 5094,
 1436: 5076,
 35: 4965,
 1435: 4962,
 36: 4907,
 1444: 4861,
 38: 4780,
 37: 4757,
 1434: 4724,
 1433: 4662,
 1445: 4581,
 39: 4542,
 40: 4464,
 41: 4416,
 1432: 4407,
 1446: 4401,
 42: 4292,
 43: 4213,
 1431: 4170,
 44: 4133,
 1447: 4123,
 1430: 4038,
 45: 4016,
 1448: 3993,
 47: 3989,
 46: 3977,
 48: 3931,
 50: 3872,
 1449: 3838,
 1429: 3836,
 51: 3817,
 49: 3807,
 53: 3693,
 52: 3659,
 1428: 3644,
 54: 3643,
 55: 3624,
 1427: 3611,
 56: 3577,
 59: 3563,
 1450: 3552,
 1426: 3521,
 63: 3449,
 57: 3444,
 58: 3438,
 60: 3435,
 1425: 3391,
 64: 3359,
 1451: 3353,
 61: 3309,
 1424: 3278,
 62: 3274,
 70: 3248,
 1452: 3247,
 67: 3226,
 65: 3221,
 66: 3207,
 68: 3160,
 71: 3133,
 1423: 3129,
 73: 3063,
 69: 3053,
 1453: 3033,
 76: 3017,
 1422: 3010,
 74: 2995,
 75: 2992,
 1454: 2986,
 72: 2983,
 81: 2962,
 80: 2958,
 79: 2957,
 77: 2948,
 78: 2907,
 1421: 2863,
 82: 2850,
 83: 2846,
 1420: 2835,
 1455: 2806,
 84: 2804,
 86: 2791,
 1419: 2768,
 87: 2751,
 90: 2709,
 88: 2709,
 1456: 2707,
 91: 2694,
 85: 2682,
 93: 2674,
 89: 2674,
 1418: 2630,
 1417: 2629,
 101: 2612,
 94: 2610,
 96: 2608,
 1457: 2597,
 92: 2583,
 95: 2563,
 103: 2557,
 98: 2551,
 100: 2540,
 99: 2537,
 97: 2532,
 102: 2503,
 1458: 2490,
 104: 2481,
 106: 2477,
 107: 2464,
 1459: 2443,
 115: 2424,
 1416: 2423,
 1415: 2407,
 111: 2404,
 108: 2385,
 105: 2364,
 112: 2349,
 1414: 2341,
 109: 2336,
 1413: 2319,
 117: 2318,
 1460: 2313,
 121: 2310,
 110: 2308,
 113: 2306,
 114: 2304,
 116: 2300,
 119: 2281,
 123: 2273,
 125: 2250,
 120: 2244,
 127: 2236,
 124: 2234,
 130: 2222,
 1411: 2216,
 1412: 2183,
 122: 2183,
 134: 2182,
 128: 2182,
 118: 2177,
 129: 2170,
 1461: 2170,
 132: 2160,
 131: 2148,
 135: 2144,
 1462: 2131,
 126: 2131,
 136: 2115,
 1410: 2086,
 142: 2083,
 1409: 2081,
 138: 2069,
 133: 2066,
 137: 2063,
 145: 2053,
 140: 2040,
 143: 2040,
 139: 2033,
 147: 2031,
 141: 2005,
 150: 2000,
 154: 1987,
 1463: 1987,
 148: 1972,
 146: 1970,
 1407: 1966,
 1464: 1958,
 144: 1957,
 1465: 1946,
 1408: 1940,
 151: 1937,
 1404: 1908,
 149: 1905,
 158: 1901,
 152: 1898,
 156: 1884,
 160: 1883,
 165: 1881,
 167: 1875,
 1406: 1874,
 583: 1872,
 568: 1872,
 565: 1869,
 153: 1861,
 563: 1858,
 577: 1858,
 155: 1857,
 162: 1854,
 1405: 1852,
 159: 1845,
 576: 1845,
 572: 1843,
 573: 1839,
 569: 1836,
 1467: 1835,
 161: 1830,
 157: 1826,
 168: 1824,
 566: 1822,
 1466: 1818,
 579: 1810,
 564: 1810,
 164: 1810,
 574: 1809,
 581: 1804,
 560: 1803,
 587: 1802,
 170: 1799,
 575: 1797,
 558: 1796,
 570: 1794,
 1403: 1789,
 1402: 1789,
 567: 1788,
 578: 1787,
 580: 1785,
 592: 1784,
 176: 1780,
 174: 1776,
 166: 1776,
 557: 1775,
 571: 1775,
 1468: 1774,
 559: 1772,
 169: 1769,
 172: 1767,
 584: 1766,
 550: 1763,
 171: 1759,
 554: 1758,
 585: 1748,
 180: 1748,
 590: 1748,
 555: 1745,
 175: 1745,
 173: 1745,
 163: 1742,
 552: 1740,
 177: 1740,
 551: 1731,
 591: 1728,
 596: 1725,
 582: 1725,
 1400: 1721,
 1401: 1717,
 595: 1715,
 561: 1715,
 178: 1708,
 184: 1708,
 594: 1708,
 562: 1707,
 545: 1705,
 197: 1701,
 588: 1699,
 556: 1695,
 544: 1691,
 1470: 1689,
 548: 1688,
 189: 1685,
 181: 1685,
 586: 1683,
 593: 1679,
 1469: 1679,
 589: 1677,
 543: 1677,
 546: 1674,
 179: 1669,
 542: 1666,
 598: 1663,
 540: 1659,
 195: 1654,
 182: 1653,
 183: 1650,
 553: 1650,
 1398: 1648,
 539: 1644,
 188: 1643,
 549: 1643,
 208: 1642,
 617: 1639,
 190: 1639,
 192: 1638,
 1399: 1637,
 601: 1635,
 187: 1635,
 547: 1632,
 1471: 1628,
 185: 1622,
 597: 1621,
 606: 1621,
 536: 1617,
 599: 1616,
 607: 1614,
 537: 1613,
 604: 1610,
 541: 1609,
 531: 1606,
 193: 1604,
 602: 1601,
 200: 1598,
 535: 1597,
 616: 1596,
 600: 1596,
 605: 1594,
 603: 1589,
 186: 1587,
 619: 1586,
 527: 1583,
 204: 1581,
 199: 1580,
 612: 1576,
 534: 1570,
 1396: 1569,
 532: 1567,
 851: 1566,
 610: 1565,
 191: 1565,
 528: 1562,
 194: 1561,
 196: 1558,
 608: 1555,
 615: 1555,
 533: 1553,
 1397: 1553,
 538: 1551,
 530: 1545,
 202: 1545,
 1473: 1543,
 609: 1537,
 209: 1537,
 1472: 1536,
 524: 1533,
 1394: 1528,
 856: 1528,
 621: 1526,
 526: 1522,
 1393: 1522,
 522: 1519,
 863: 1518,
 207: 1518,
 611: 1515,
 201: 1513,
 210: 1512,
 614: 1511,
 620: 1511,
 214: 1510,
 211: 1509,
 215: 1508,
 613: 1506,
 1395: 1505,
 858: 1504,
 515: 1498,
 205: 1497,
 834: 1496,
 206: 1495,
 513: 1494,
 222: 1493,
 865: 1492,
 628: 1492,
 521: 1491,
 624: 1491,
 227: 1491,
 877: 1490,
 1388: 1489,
 847: 1488,
 623: 1487,
 198: 1487,
 213: 1487,
 203: 1487,
 529: 1486,
 1392: 1484,
 217: 1482,
 627: 1482,
 850: 1482,
 860: 1480,
 625: 1477,
 517: 1475,
 842: 1475,
 220: 1474,
 861: 1471,
 525: 1469,
 523: 1468,
 855: 1466,
 630: 1466,
 866: 1460,
 848: 1460,
 618: 1458,
 226: 1458,
 1474: 1456,
 212: 1456,
 862: 1455,
 629: 1454,
 230: 1451,
 845: 1451,
 216: 1449,
 1391: 1449,
 846: 1447,
 853: 1446,
 859: 1445,
 632: 1444,
 869: 1443,
 871: 1440,
 806: 1439,
 852: 1439,
 218: 1438,
 622: 1436,
 879: 1433,
 221: 1432,
 520: 1430,
 864: 1429,
 626: 1429,
 637: 1428,
 511: 1428,
 849: 1428,
 219: 1428,
 844: 1427,
 835: 1427,
 225: 1427,
 857: 1427,
 1389: 1426,
 514: 1425,
 510: 1425,
 829: 1424,
 508: 1424,
 839: 1423,
 873: 1423,
 229: 1420,
 823: 1419,
 634: 1419,
 1390: 1417,
 867: 1417,
 872: 1416,
 1475: 1415,
 836: 1414,
 843: 1410,
 831: 1407,
 516: 1407,
 633: 1407,
 813: 1405,
 880: 1404,
 638: 1404,
 841: 1404,
 635: 1403,
 854: 1403,
 224: 1402,
 838: 1401,
 828: 1398,
 631: 1397,
 223: 1394,
 878: 1393,
 868: 1393,
 814: 1392,
 518: 1389,
 874: 1388,
 647: 1386,
 870: 1385,
 1387: 1385,
 228: 1383,
 825: 1382,
 512: 1381,
 840: 1381,
 830: 1380,
 807: 1379,
 519: 1379,
 887: 1379,
 233: 1378,
 876: 1376,
 816: 1374,
 832: 1373,
 875: 1373,
 881: 1370,
 234: 1369,
 506: 1369,
 236: 1368,
 237: 1367,
 656: 1367,
 503: 1367,
 241: 1365,
 822: 1363,
 650: 1361,
 636: 1360,
 827: 1360,
 232: 1359,
 1478: 1358,
 658: 1358,
 499: 1357,
 1476: 1357,
 248: 1357,
 882: 1356,
 643: 1356,
 238: 1356,
 235: 1355,
 820: 1355,
 824: 1354,
 833: 1354,
 495: 1354,
 491: 1353,
 804: 1352,
 231: 1351,
 242: 1351,
 639: 1348,
 640: 1347,
 817: 1347,
 644: 1346,
 826: 1345,
 652: 1345,
 883: 1344,
 505: 1341,
 507: 1340,
 889: 1340,
 504: 1340,
 891: 1340,
 509: 1340,
 837: 1338,
 653: 1338,
 818: 1338,
 815: 1336,
 497: 1336,
 1384: 1336,
 494: 1336,
 811: 1335,
 254: 1334,
 651: 1334,
 795: 1333,
 819: 1333,
 797: 1331,
 812: 1331,
 244: 1329,
 1385: 1329,
 821: 1328,
 502: 1327,
 501: 1325,
 642: 1325,
 810: 1324,
 1477: 1324,
 884: 1323,
 793: 1322,
 1386: 1321,
 496: 1320,
 809: 1320,
 808: 1319,
 790: 1318,
 655: 1317,
 799: 1315,
 645: 1312,
 886: 1311,
 641: 1310,
 648: 1309,
 500: 1307,
 801: 1307,
 785: 1307,
 646: 1306,
 492: 1303,
 885: 1302,
 789: 1301,
 1479: 1301,
 805: 1296,
 498: 1294,
 802: 1292,
 486: 1292,
 245: 1291,
 251: 1290,
 893: 1290,
 888: 1290,
 657: 1289,
 243: 1289,
 781: 1289,
 490: 1289,
 483: 1289,
 250: 1287,
 1480: 1287,
 249: 1284,
 661: 1284,
 788: 1284,
 900: 1282,
 796: 1279,
 493: 1279,
 798: 1278,
 262: 1277,
 794: 1275,
 256: 1275,
 1382: 1275,
 791: 1275,
 649: 1274,
 253: 1274,
 660: 1273,
 257: 1270,
 892: 1269,
 786: 1268,
 777: 1267,
 239: 1266,
 783: 1266,
 792: 1266,
 901: 1264,
 1481: 1263,
 481: 1261,
 665: 1260,
 894: 1259,
 488: 1258,
 662: 1257,
 890: 1257,
 2877: 1256,
 803: 1255,
 1383: 1254,
 800: 1254,
 654: 1254,
 252: 1252,
 247: 1250,
 480: 1250,
 787: 1249,
 258: 1246,
 489: 1244,
 663: 1243,
 895: 1242,
 668: 1241,
 261: 1241,
 240: 1241,
 487: 1240,
 659: 1240,
 1482: 1240,
 246: 1238,
 761: 1236,
 485: 1236,
 898: 1235,
 776: 1233,
 1381: 1233,
 482: 1233,
 474: 1232,
 255: 1232,
 2879: 1231,
 270: 1228,
 266: 1228,
 896: 1225,
 782: 1224,
 484: 1223,
 2880: 1221,
 478: 1220,
 1379: 1220,
 479: 1218,
 264: 1217,
 770: 1215,
 897: 1214,
 477: 1213,
 899: 1213,
 278: 1212,
 260: 1211,
 1373: 1210,
 772: 1209,
 664: 1208,
 766: 1206,
 670: 1206,
 692: 1203,
 666: 1203,
 470: 1203,
 775: 1203,
 774: 1202,
 674: 1202,
 1378: 1202,
 2881: 1202,
 475: 1202,
 2876: 1201,
 471: 1200,
 905: 1200,
 784: 1199,
 2878: 1198,
 769: 1198,
 2874: 1198,
 773: 1197,
 1483: 1197,
 259: 1197,
 1485: 1196,
 907: 1196,
 779: 1196,
 269: 1195,
 271: 1194,
 771: 1194,
 281: 1194,
 767: 1193,
 1377: 1192,
 469: 1190,
 1380: 1190,
 902: 1190,
 263: 1189,
 467: 1188,
 909: 1186,
 265: 1186,
 1376: 1185,
 2883: 1185,
 743: 1184,
 268: 1184,
 778: 1184,
 458: 1183,
 1484: 1183,
 676: 1181,
 758: 1181,
 667: 1179,
 764: 1178,
 733: 1178,
 701: 1177,
 762: 1177,
 721: 1176,
 672: 1176,
 727: 1175,
 463: 1174,
 683: 1174,
 914: 1174,
 274: 1174,
 906: 1173,
 750: 1172,
 691: 1171,
 768: 1169,
 710: 1169,
 699: 1169,
 756: 1169,
 735: 1168,
 1374: 1167,
 763: 1167,
 697: 1167,
 279: 1167,
 267: 1165,
 706: 1163,
 289: 1163,
 472: 1162,
 728: 1162,
 716: 1161,
 684: 1161,
 284: 1160,
 476: 1160,
 669: 1159,
 473: 1159,
 682: 1158,
 780: 1157,
 904: 1156,
 738: 1156,
 755: 1156,
 275: 1156,
 748: 1155,
 280: 1155,
 760: 1155,
 688: 1154,
 671: 1154,
 1375: 1154,
 757: 1154,
 680: 1153,
 677: 1152,
 687: 1152,
 673: 1152,
 2873: 1151,
 273: 1151,
 696: 1150,
 461: 1149,
 679: 1148,
 713: 1148,
 720: 1148,
 283: 1148,
 913: 1148,
 1486: 1148,
 693: 1147,
 703: 1146,
 690: 1146,
 921: 1145,
 742: 1145,
 686: 1145,
 288: 1145,
 911: 1145,
 685: 1144,
 460: 1144,
 707: 1143,
 903: 1143,
 702: 1142,
 754: 1141,
 908: 1141,
 745: 1140,
 705: 1140,
 751: 1140,
 752: 1139,
 459: 1139,
 678: 1138,
 466: 1138,
 759: 1137,
 746: 1136,
 916: 1136,
 704: 1135,
 731: 1134,
 719: 1134,
 272: 1133,
 725: 1133,
 465: 1132,
 915: 1132,
 753: 1132,
 722: 1132,
 723: 1131,
 1368: 1130,
 712: 1129,
 2875: 1129,
 304: 1129,
 1488: 1129,
 747: 1127,
 1372: 1127,
 749: 1127,
 457: 1127,
 675: 1126,
 765: 1126,
 2882: 1126,
 729: 1124,
 276: 1124,
 293: 1123,
 1371: 1120,
 694: 1119,
 291: 1119,
 912: 1118,
 681: 1116,
 736: 1116,
 285: 1116,
 715: 1114,
 717: 1114,
 282: 1113,
 919: 1112,
 714: 1110,
 1489: 1109,
 277: 1108,
 1370: 1106,
 744: 1106,
 739: 1104,
 724: 1104,
 740: 1103,
 1487: 1103,
 303: 1098,
 918: 1095,
 464: 1095,
 287: 1095,
 299: 1095,
 730: 1093,
 296: 1092,
 695: 1091,
 448: 1090,
 452: 1090,
 2872: 1089,
 1369: 1089,
 689: 1089,
 2884: 1088,
 456: 1087,
 718: 1086,
 726: 1086,
 917: 1085,
 290: 1084,
 708: 1083,
 453: 1082,
 462: 1082,
 737: 1080,
 910: 1079,
 698: 1079,
 741: 1078,
 1494: 1078,
 1363: 1078,
 923: 1077,
 734: 1077,
 432: 1073,
 302: 1073,
 709: 1071,
 711: 1071,
 925: 1069,
 309: 1069,
 449: 1069,
 1367: 1069,
 2885: 1067,
 300: 1066,
 700: 1066,
 438: 1066,
 1365: 1065,
 455: 1064,
 732: 1063,
 920: 1062,
 446: 1061,
 454: 1060,
 468: 1053,
 305: 1052,
 1366: 1051,
 298: 1049,
 441: 1049,
 930: 1046,
 1490: 1045,
 924: 1044,
 2871: 1043,
 451: 1042,
 311: 1041,
 1364: 1041,
 444: 1040,
 1491: 1039,
 307: 1038,
 427: 1038,
 440: 1038,
 313: 1037,
 933: 1037,
 294: 1037,
 935: 1036,
 2886: 1036,
 442: 1036,
 1362: 1034,
 301: 1034,
 295: 1034,
 424: 1033,
 312: 1032,
 297: 1028,
 922: 1027,
 426: 1026,
 443: 1026,
 308: 1025,
 430: 1023,
 447: 1023,
 1493: 1022,
 286: 1022,
 932: 1022,
 408: 1022,
 926: 1020,
 315: 1019,
 314: 1017,
 415: 1016,
 927: 1015,
 292: 1015,
 323: 1014,
 450: 1010,
 928: 1009,
 306: 1009,
 1361: 1005,
 429: 1003,
 445: 1002,
 938: 1002,
 435: 1001,
 929: 1000,
 422: 999,
 322: 999,
 439: 996,
 418: 995,
 413: 993,
 316: 993,
 425: 993,
 409: 992,
 310: 992,
 1359: 990,
 1351: 989,
 940: 989,
 1356: 989,
 1492: 986,
 392: 986,
 436: 986,
 328: 984,
 320: 984,
 936: 981,
 934: 979,
 944: 978,
 423: 978,
 319: 976,
 1360: 976,
 937: 974,
 434: 974,
 431: 973,
 421: 972,
 395: 971,
 2868: 970,
 ...}

In [11]:
##Booking time different in hours
df['booking_time_diff_hr'].value_counts().to_dict()

{0: 4849856,
 1: 164914,
 23: 152962,
 24: 132454,
 2: 118199,
 9: 104854,
 3: 90789,
 10: 86794,
 8: 84454,
 14: 83715,
 13: 80005,
 4: 71379,
 11: 69332,
 12: 69267,
 7: 64610,
 15: 61892,
 5: 58059,
 22: 56709,
 6: 55287,
 16: 45075,
 21: 42289,
 47: 41525,
 25: 38067,
 48: 36781,
 20: 36559,
 17: 36124,
 19: 33701,
 18: 32710,
 71: 27538,
 72: 24658,
 26: 23932,
 46: 20902,
 27: 17593,
 45: 17142,
 49: 16426,
 38: 16319,
 95: 15844,
 37: 15186,
 39: 15048,
 44: 14897,
 96: 14258,
 43: 14004,
 28: 13903,
 40: 13586,
 70: 13131,
 36: 13019,
 42: 12926,
 41: 12516,
 50: 11945,
 35: 11789,
 29: 11770,
 34: 11479,
 33: 11356,
 119: 10863,
 62: 10769,
 73: 10731,
 32: 10583,
 30: 10279,
 69: 10150,
 31: 9997,
 120: 9641,
 63: 9561,
 61: 9401,
 51: 9313,
 68: 8957,
 94: 8381,
 143: 8335,
 167: 8252,
 64: 8089,
 60: 7865,
 67: 7802,
 52: 7755,
 144: 7645,
 74: 7590,
 168: 7571,
 66: 7370,
 65: 7293,
 97: 7220,
 93: 6805,
 59: 6594,
 53: 6488,
 58: 6294,
 118: 6171,
 75: 6029,
 57: 5957,
 54: 5853,
 92: 5742,
 56: 5646,
 55: 5634,
 121: 5414,
 86: 5362,
 98: 5296,
 91: 5155,
 87: 5069,
 117: 4907,
 76: 4866,
 142: 4832,
 85: 4804,
 90: 4780,
 88: 4715,
 89: 4476,
 191: 4409,
 166: 4388,
 145: 4261,
 84: 4226,
 116: 4221,
 99: 4192,
 77: 4146,
 192: 4086,
 122: 4069,
 141: 3969,
 83: 3952,
 82: 3933,
 81: 3871,
 115: 3833,
 78: 3714,
 79: 3670,
 169: 3616,
 80: 3586,
 110: 3560,
 114: 3477,
 140: 3441,
 100: 3430,
 111: 3419,
 165: 3405,
 123: 3337,
 112: 3275,
 109: 3261,
 113: 3244,
 215: 3234,
 146: 3228,
 101: 3056,
 139: 2994,
 164: 2967,
 216: 2943,
 190: 2924,
 108: 2905,
 239: 2791,
 170: 2749,
 124: 2746,
 107: 2741,
 240: 2741,
 102: 2738,
 105: 2718,
 106: 2716,
 138: 2667,
 104: 2638,
 134: 2610,
 147: 2593,
 103: 2568,
 163: 2539,
 137: 2529,
 135: 2519,
 263: 2503,
 193: 2498,
 136: 2498,
 125: 2351,
 335: 2346,
 264: 2344,
 189: 2340,
 133: 2325,
 336: 2294,
 148: 2211,
 162: 2197,
 214: 2195,
 287: 2178,
 161: 2175,
 132: 2157,
 171: 2156,
 126: 2118,
 159: 2072,
 188: 2034,
 217: 2026,
 128: 2024,
 158: 2023,
 288: 2022,
 130: 2016,
 131: 2013,
 194: 2000,
 129: 1983,
 311: 1976,
 160: 1963,
 238: 1959,
 312: 1958,
 149: 1948,
 127: 1929,
 213: 1911,
 157: 1863,
 187: 1785,
 172: 1780,
 150: 1746,
 212: 1730,
 241: 1706,
 262: 1680,
 237: 1652,
 156: 1645,
 218: 1617,
 195: 1600,
 155: 1595,
 153: 1594,
 265: 1591,
 186: 1588,
 152: 1554,
 185: 1520,
 286: 1520,
 151: 1518,
 154: 1517,
 184: 1493,
 173: 1466,
 310: 1462,
 211: 1461,
 236: 1435,
 183: 1423,
 242: 1419,
 219: 1417,
 360: 1414,
 289: 1414,
 334: 1407,
 359: 1398,
 261: 1389,
 196: 1387,
 181: 1380,
 182: 1366,
 235: 1352,
 174: 1347,
 210: 1323,
 337: 1287,
 285: 1285,
 176: 1269,
 313: 1258,
 175: 1241,
 333: 1228,
 177: 1227,
 180: 1227,
 266: 1222,
 197: 1222,
 220: 1219,
 260: 1215,
 243: 1199,
 178: 1194,
 207: 1181,
 208: 1177,
 407: 1170,
 209: 1161,
 383: 1153,
 290: 1149,
 179: 1146,
 206: 1144,
 309: 1130,
 384: 1103,
 284: 1102,
 259: 1101,
 503: 1076,
 234: 1069,
 232: 1064,
 408: 1052,
 198: 1037,
 205: 1035,
 358: 1031,
 231: 1029,
 308: 1025,
 504: 1014,
 338: 1010,
 431: 1004,
 233: 1001,
 230: 997,
 244: 995,
 258: 993,
 267: 990,
 314: 986,
 204: 973,
 202: 965,
 201: 963,
 332: 962,
 203: 962,
 221: 960,
 432: 959,
 361: 959,
 291: 954,
 283: 947,
 245: 944,
 257: 942,
 199: 936,
 222: 932,
 456: 928,
 268: 921,
 455: 911,
 200: 908,
 315: 900,
 229: 894,
 224: 881,
 307: 880,
 226: 874,
 228: 869,
 479: 868,
 480: 867,
 255: 863,
 357: 858,
 282: 857,
 225: 856,
 256: 854,
 254: 851,
 331: 847,
 227: 847,
 223: 840,
 281: 826,
 382: 825,
 292: 822,
 253: 809,
 362: 803,
 269: 793,
 385: 792,
 406: 788,
 409: 787,
 430: 787,
 306: 780,
 280: 779,
 339: 778,
 330: 758,
 381: 758,
 303: 753,
 278: 752,
 356: 746,
 246: 737,
 247: 737,
 405: 734,
 250: 733,
 249: 730,
 270: 730,
 293: 729,
 251: 728,
 279: 727,
 305: 720,
 316: 720,
 252: 719,
 502: 712,
 386: 708,
 527: 702,
 454: 694,
 380: 693,
 355: 687,
 528: 684,
 433: 678,
 328: 677,
 478: 671,
 277: 668,
 248: 664,
 304: 662,
 271: 660,
 363: 654,
 329: 652,
 273: 652,
 276: 652,
 317: 651,
 302: 649,
 457: 649,
 272: 648,
 505: 646,
 340: 643,
 551: 640,
 429: 639,
 379: 633,
 410: 629,
 274: 626,
 354: 625,
 294: 625,
 326: 624,
 327: 612,
 434: 608,
 671: 605,
 404: 604,
 353: 602,
 300: 600,
 387: 596,
 295: 594,
 301: 593,
 275: 590,
 501: 587,
 481: 586,
 296: 578,
 299: 575,
 672: 575,
 341: 575,
 298: 574,
 552: 569,
 453: 566,
 325: 563,
 428: 562,
 403: 553,
 297: 553,
 318: 552,
 319: 552,
 575: 549,
 364: 548,
 576: 545,
 411: 542,
 342: 539,
 321: 539,
 352: 537,
 599: 537,
 320: 536,
 477: 534,
 452: 530,
 378: 526,
 351: 524,
 458: 524,
 526: 515,
 476: 510,
 324: 506,
 600: 504,
 623: 503,
 529: 501,
 427: 499,
 322: 498,
 323: 497,
 376: 492,
 402: 491,
 343: 491,
 388: 489,
 377: 486,
 451: 485,
 500: 484,
 550: 484,
 482: 483,
 648: 482,
 506: 480,
 624: 480,
 435: 478,
 365: 478,
 374: 475,
 349: 472,
 426: 469,
 375: 466,
 647: 466,
 350: 464,
 345: 464,
 412: 458,
 574: 455,
 401: 449,
 347: 446,
 344: 445,
 366: 443,
 389: 443,
 483: 443,
 525: 441,
 695: 438,
 577: 432,
 549: 432,
 413: 431,
 696: 430,
 459: 430,
 670: 427,
 598: 426,
 400: 423,
 553: 423,
 399: 421,
 449: 421,
 348: 418,
 554: 413,
 475: 413,
 424: 409,
 346: 408,
 450: 406,
 839: 406,
 474: 405,
 507: 404,
 373: 403,
 523: 401,
 498: 399,
 508: 399,
 719: 397,
 460: 396,
 524: 395,
 436: 394,
 371: 392,
 367: 392,
 530: 391,
 368: 390,
 390: 389,
 499: 389,
 398: 389,
 372: 387,
 720: 387,
 601: 382,
 622: 382,
 673: 379,
 425: 378,
 649: 377,
 447: 371,
 625: 371,
 393: 370,
 423: 370,
 573: 369,
 461: 368,
 392: 367,
 391: 367,
 446: 366,
 646: 366,
 744: 365,
 421: 365,
 743: 364,
 548: 363,
 484: 362,
 472: 361,
 369: 360,
 394: 357,
 397: 357,
 437: 355,
 840: 354,
 596: 352,
 414: 352,
 767: 349,
 621: 349,
 597: 349,
 396: 349,
 497: 349,
 674: 343,
 416: 342,
 422: 339,
 694: 336,
 438: 336,
 370: 336,
 440337: 335,
 572: 334,
 578: 333,
 395: 331,
 420: 331,
 602: 330,
 445: 330,
 417: 328,
 815: 328,
 522: 328,
 415: 326,
 496: 326,
 448: 324,
 697: 323,
 620: 319,
 494: 319,
 547: 319,
 555: 318,
 462: 317,
 473: 317,
 645: 315,
 768: 315,
 418: 314,
 603: 314,
 485: 314,
 444: 314,
 669: 312,
 439: 311,
 791: 311,
 486: 310,
 465: 310,
 493: 306,
 650: 304,
 532: 302,
 471: 302,
 440385: 302,
 627: 301,
 864: 301,
 521: 301,
 556: 301,
 469: 300,
 863: 300,
 644: 298,
 816: 298,
 626: 297,
 470: 296,
 463: 296,
 440: 294,
 571: 294,
 721: 293,
 466: 293,
 441: 292,
 533: 287,
 419: 287,
 440386: 286,
 509: 286,
 442: 286,
 668: 284,
 495: 284,
 531: 283,
 546: 282,
 443: 282,
 580: 280,
 718: 279,
 594: 279,
 792: 279,
 693: 276,
 440338: 275,
 579: 274,
 468: 274,
 489: 271,
 487: 271,
 464: 269,
 911: 267,
 520: 266,
 519: 266,
 595: 264,
 545: 263,
 741: 263,
 492: 262,
 742: 261,
 651: 258,
 745: 258,
 769: 258,
 518: 257,
 717: 257,
 581: 255,
 491: 255,
 766: 255,
 517: 254,
 628: 253,
 619: 253,
 510: 252,
 643: 252,
 716: 251,
 1007: 251,
 543: 251,
 675: 250,
 790: 249,
 544: 248,
 542: 248,
 814: 248,
 513: 248,
 692: 247,
 514: 247,
 698: 247,
 511: 247,
 1008: 246,
 789: 245,
 642: 245,
 838: 245,
 793: 244,
 516: 242,
 488: 242,
 557: 242,
 604: 242,
 667: 242,
 618: 239,
 568: 239,
 887: 238,
 841: 237,
 567: 237,
 699: 237,
 512: 237,
 467: 236,
 641: 234,
 722: 233,
 570: 233,
 534: 233,
 912: 232,
 765: 230,
 440336: 230,
 440339: 230,
 666: 228,
 770: 228,
 569: 227,
 817: 226,
 591: 223,
 440346: 223,
 984: 223,
 490: 222,
 541: 221,
 440340: 221,
 935: 221,
 959: 219,
 440345: 219,
 605: 219,
 862: 219,
 888: 219,
 665: 218,
 615: 217,
 723: 217,
 652: 216,
 593: 216,
 559: 213,
 813: 211,
 740: 211,
 440347: 210,
 535: 210,
 440384: 210,
 566: 210,
 691: 210,
 714: 209,
 865: 209,
 592: 209,
 616: 208,
 936: 208,
 812: 208,
 614: 207,
 539: 207,
 582: 206,
 590: 206,
 818: 204,
 739: 204,
 960: 203,
 536: 202,
 746: 201,
 583: 199,
 837: 199,
 676: 199,
 515: 199,
 1006: 198,
 440387: 198,
 1032: 198,
 565: 197,
 690: 196,
 629: 196,
 794: 196,
 836: 195,
 747: 195,
 630: 195,
 700: 195,
 889: 194,
 861: 194,
 689: 194,
 764: 193,
 788: 193,
 558: 193,
 538: 192,
 560: 191,
 983: 190,
 588: 189,
 663: 189,
 664: 189,
 617: 188,
 842: 188,
 910: 188,
 639: 188,
 886: 187,
 662: 187,
 653: 187,
 561: 187,
 885: 186,
 640: 185,
 1175: 185,
 537: 184,
 609: 184,
 440341: 184,
 587: 183,
 890: 183,
 1031: 182,
 913: 182,
 771: 181,
 677: 181,
 933: 181,
 914: 181,
 715: 179,
 584: 179,
 934: 179,
 589: 178,
 562: 178,
 611: 178,
 1080: 178,
 678: 178,
 440344: 177,
 1056: 176,
 1103: 176,
 540: 175,
 762: 175,
 654: 175,
 982: 175,
 835: 175,
 961: 175,
 958: 175,
 636: 174,
 1176: 173,
 631: 173,
 687: 173,
 564: 173,
 1079: 172,
 440348: 172,
 661: 172,
 724: 171,
 786: 171,
 613: 171,
 763: 171,
 1009: 170,
 612: 170,
 638: 170,
 607: 169,
 1128: 169,
 585: 168,
 819: 168,
 1005: 168,
 659: 168,
 884: 168,
 608: 167,
 866: 167,
 1055: 167,
 749: 167,
 909: 166,
 795: 166,
 787: 165,
 440394: 164,
 1030: 164,
 634: 164,
 563: 164,
 713: 163,
 937: 162,
 701: 162,
 860: 162,
 606: 159,
 688: 159,
 843: 157,
 633: 157,
 586: 157,
 737: 157,
 440342: 156,
 986: 156,
 985: 156,
 680: 156,
 750: 156,
 637: 156,
 1104: 155,
 635: 155,
 844: 155,
 981: 154,
 440393: 154,
 1054: 154,
 1177: 153,
 1033: 153,
 712: 153,
 1127: 153,
 711: 153,
 748: 152,
 796: 151,
 686: 151,
 440395: 151,
 440409: 150,
 702: 150,
 1004: 150,
 1078: 150,
 657: 149,
 738: 149,
 656: 149,
 1344: 148,
 679: 148,
 1152: 148,
 1343: 147,
 915: 147,
 707: 147,
 1199: 147,
 1174: 147,
 810: 147,
 440343: 147,
 632: 146,
 735: 146,
 785: 146,
 832: 145,
 682: 144,
 736: 144,
 655: 144,
 938: 144,
 681: 144,
 704: 143,
 1010: 142,
 908: 142,
 1200: 142,
 957: 142,
 1150: 142,
 683: 142,
 811: 141,
 867: 141,
 660: 141,
 1034: 140,
 1105: 139,
 1151: 139,
 845: 139,
 684: 139,
 758: 139,
 773: 138,
 772: 138,
 759: 138,
 1057: 138,
 1224: 138,
 962: 138,
 761: 137,
 710: 137,
 760: 137,
 725: 137,
 939: 136,
 892: 136,
 821: 136,
 868: 136,
 610: 136,
 440410: 136,
 1081: 135,
 891: 135,
 800: 135,
 1029: 135,
 733: 134,
 685: 134,
 757: 133,
 1102: 133,
 1077: 133,
 807: 133,
 809: 133,
 709: 133,
 955: 132,
 1058: 132,
 440419: 132,
 980: 132,
 440349: 131,
 1126: 131,
 808: 131,
 734: 131,
 784: 131,
 833: 131,
 883: 131,
 658: 130,
 706: 130,
 834: 130,
 854: 130,
 932: 130,
 906: 130,
 703: 130,
 907: 129,
 729: 129,
 806: 128,
 797: 128,
 1011: 128,
 1247: 128,
 781: 128,
 727: 127,
 1271: 127,
 730: 127,
 440388: 126,
 823: 126,
 440418: 125,
 705: 125,
 859: 125,
 846: 124,
 440491: 124,
 1319: 123,
 726: 123,
 440434: 123,
 1129: 123,
 1320: 122,
 820: 122,
 954: 122,
 1391: 121,
 1153: 121,
 731: 120,
 440443: 120,
 857: 120,
 728: 119,
 1053: 119,
 774: 119,
 440389: 118,
 1223: 118,
 1125: 118,
 440335: 118,
 880: 118,
 1083: 117,
 1511: 117,
 751: 117,
 754: 117,
 931: 116,
 708: 116,
 440411: 116,
 1295: 116,
 956: 116,
 904: 116,
 881: 116,
 777: 116,
 752: 116,
 440467: 115,
 831: 115,
 776: 115,
 1100: 114,
 1272: 114,
 963: 114,
 830: 114,
 1249: 114,
 1130: 113,
 798: 113,
 1368: 113,
 1028: 113,
 916: 113,
 440433: 113,
 1201: 112,
 1250: 112,
 783: 112,
 1248: 112,
 732: 112,
 1246: 112,
 869: 112,
 440442: 111,
 1082: 111,
 1027: 111,
 1124: 111,
 829: 111,
 847: 111,
 929: 110,
 978: 109,
 930: 109,
 989: 109,
 964: 109,
 ...}

### We observe that there are 8315382 - 4335828 = 39,79,554 booking that happen in less than 1 hour of request by a user

In [12]:
len(df)

8315382

In [13]:
### Handling Case 1: Re-booking Again to Same Location within 1hour by same user

df = df[~((df.duplicated(subset=['number','pick_lat','pick_lng'],keep=False)) & (df.booking_time_diff_hr<=1))]

In [14]:
## Before removing Row Count
len(df)

4335828

###  Removed 3979554 rows in `Case1` we now have 4335828

In [15]:
df.to_csv('./../Data/data_checkpoint/preprocessed_2.csv',index = False, compression = 'gzip')

### Handling Case2: One user Books rides are different lat-long within 8mins time (ride time + driver arrival time)
#### Fraud User
#### Human error booking

In [16]:
df = pd.read_csv('./../Data/data_checkpoint/preprocessed_2.csv', compression = 'gzip')

In [17]:
print("Number of rides booked by same customer within 8mins time: {}".format(len(df[(df.booking_time_diff_min<8)])))
df = df[(df.booking_time_diff_min>=8)]

Number of rides booked by same customer within 8mins time: 611891

### Assuming earth as ellipsoids, calculating geodesic distance b/w pickup and drop latitude and longitude

The geodesic distance is the shortest distance on the surface of an ellipsoidal model of the earth. The default algorithm uses the method is given by [Karney (2013)](https://link.springer.com/article/10.1007/s00190-012-0578-z) (geodesic); this is accurate to round-off and always converges.

`Check Learning Resources Folder in Documentation Folder`

In [18]:
%%time
def geodestic_distance(pick_lat, pick_lng, drop_lat, drop_lng):
    # 1mile = 1.60934 Kms
    return round(geodesic((pick_lat, pick_lng), (drop_lat, drop_lng)).miles*1.60934,2)

df['geodesic_distance'] = np.vectorize(geodestic_distance)(df['pick_lat'],df['pick_lng'],df['drop_lat'],df['drop_lng'])

CPU times: user 22min 31s, sys: 3.05 s, total: 22min 34s
Wall time: 22min 36s

##### Number of rides booked but same customer within 8mins time: 875816

In [19]:
df[df['geodesic_distance']<=0.5]['geodesic_distance'].value_counts()

0.00    6619
0.01    2492
0.02    2011
0.03    1371
0.50    1210
0.04    1090
0.47    1076
0.49    1067
0.48    1064
0.46    1056
0.44     895
0.45     881
0.05     877
0.43     845
0.41     764
0.39     758
0.06     752
0.42     748
0.40     746
0.38     682
0.37     675
0.07     655
0.36     641
0.33     594
0.08     592
0.34     585
0.35     582
0.09     549
0.32     542
0.31     530
0.10     498
0.11     492
0.30     490
0.29     476
0.12     457
0.28     447
0.26     439
0.27     432
0.14     410
0.17     408
0.21     404
0.20     397
0.24     391
0.22     390
0.13     384
0.18     369
0.23     368
0.15     364
0.19     355
0.25     342
0.16     339
Name: geodesic_distance, dtype: int64

### Handle Case 2.1: Removing ride request less than 0.05 miles = 50meters

In [20]:
print("Number of Rides Requests less than 50meters: {}".format(len(df[df.geodesic_distance<=0.05])))

Number of Rides Requests less than 50meters: 14460

In [21]:
df = df[df.geodesic_distance>0.05]
df

,index,ts,number,pick_lat,pick_lng,drop_lat,drop_lng,hour,mins,day,month,year,dayofweek,booking_timestamp,shift_booking_ts,booking_time_diff_hr,booking_time_diff_min,geodesic_distance
0,2374378,2020-10-10 07:34:16,-1,12.975773,77.571070,12.878468,77.445330,7,34,10,10,2020,5,1602315256,0,445087,26705254,17.38
1,2405894,2020-10-11 08:23:42,-1,12.930813,77.609530,12.960320,77.587210,8,23,11,10,2020,6,1602404622,1602315256,24,1489,4.06
2,2406076,2020-10-11 11:57:17,-1,12.960213,77.587460,12.930824,77.609610,11,57,11,10,2020,6,1602417437,1602404636,3,213,4.04
3,2500477,2020-10-16 17:51:07,-1,12.924353,77.549410,12.932216,77.581825,17,51,16,10,2020,4,1602870667,1602417451,125,7553,3.62
4,2694503,2020-10-30 09:00:44,-1,12.945731,77.622500,12.973030,77.616840,9,0,30,10,2020,4,1604048444,1602870685,327,19629,3.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335823,5768115,2021-02-12 19:37:11,99999,13.029848,77.593400,13.063751,77.589850,19,37,12,2,2021,4,1613158631,1613068718,24,1498,3.77
4335824,6102760,2021-02-19 20:43:25,99999,13.029296,77.592580,12.927923,77.627106,20,43,19,2,2021,4,1613767405,1613158631,169,10146,11.82
4335825,6137206,2021-02-20 17:34:45,99999,12.907576,77.600685,12.925874,77.607620,17,34,20,2,2021,5,1613842485,1613767405,20,1251,2.16
4335826,6555089,2021-02-27 08:26:23,99999,12.956665,77.521870,12.948099,77.562990,8,26,27,2,2021,5,1614414383,1613842485,158,9531,4.56
4335827,6888302,2021-03-04 19:13:13,99999,12.987954,77.555880,13.065613,77.559910,19,13,4,3,2021,3,1614885193,1614414383,130,7846,8.60

In [22]:
len(df)

3709477

In [23]:
df.to_csv('./../Data/data_checkpoint/preprocessed_3.csv',index = False, compression = 'gzip')

### Handle Case3: Rides request in non-operational regions
OLA Bikes OPERATION CITY (Bangalore)

### Ride requests due to some bug or crash in app.
<hr>

#### India: 'boundingbox': ['6.2325274', '35.6745457', '68.1113787', '97.395561']
#### Bangalore:'boundingbox': ['12.8340125', '13.1436649', '77.4601025', '77.7840515']
#### Karnataka: 'boundingbox': ['11.5945587', '18.4767308', '74.0543908', '78.588083']
Source: openstreetmap

In [24]:
df = pd.read_csv('./../Data/data_checkpoint/preprocessed_3.csv', compression = 'gzip')
location = geolocator.geocode("India")
location.raw

{'place_id': 310001725,
 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
 'osm_type': 'relation',
 'osm_id': 304716,
 'boundingbox': ['6.2325274', '35.5232328', '68.1113787', '97.395561'],
 'lat': '22.3511148',
 'lon': '78.6677428',
 'display_name': 'India',
 'class': 'boundary',
 'type': 'administrative',
 'importance': 0.957689135880987,
 'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'}

In [25]:
df

,index,ts,number,pick_lat,pick_lng,drop_lat,drop_lng,hour,mins,day,month,year,dayofweek,booking_timestamp,shift_booking_ts,booking_time_diff_hr,booking_time_diff_min,geodesic_distance
0,2374378,2020-10-10 07:34:16,-1,12.975773,77.571070,12.878468,77.445330,7,34,10,10,2020,5,1602315256,0,445087,26705254,17.38
1,2405894,2020-10-11 08:23:42,-1,12.930813,77.609530,12.960320,77.587210,8,23,11,10,2020,6,1602404622,1602315256,24,1489,4.06
2,2406076,2020-10-11 11:57:17,-1,12.960213,77.587460,12.930824,77.609610,11,57,11,10,2020,6,1602417437,1602404636,3,213,4.04
3,2500477,2020-10-16 17:51:07,-1,12.924353,77.549410,12.932216,77.581825,17,51,16,10,2020,4,1602870667,1602417451,125,7553,3.62
4,2694503,2020-10-30 09:00:44,-1,12.945731,77.622500,12.973030,77.616840,9,0,30,10,2020,4,1604048444,1602870685,327,19629,3.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3709472,5768115,2021-02-12 19:37:11,99999,13.029848,77.593400,13.063751,77.589850,19,37,12,2,2021,4,1613158631,1613068718,24,1498,3.77
3709473,6102760,2021-02-19 20:43:25,99999,13.029296,77.592580,12.927923,77.627106,20,43,19,2,2021,4,1613767405,1613158631,169,10146,11.82
3709474,6137206,2021-02-20 17:34:45,99999,12.907576,77.600685,12.925874,77.607620,17,34,20,2,2021,5,1613842485,1613767405,20,1251,2.16
3709475,6555089,2021-02-27 08:26:23,99999,12.956665,77.521870,12.948099,77.562990,8,26,27,2,2021,5,1614414383,1613842485,158,9531,4.56
3709476,6888302,2021-03-04 19:13:13,99999,12.987954,77.555880,13.065613,77.559910,19,13,4,3,2021,3,1614885193,1614414383,130,7846,8.60

In [26]:
## How many rides outside india?
df[(df.pick_lat<=6.2325274) | (df.pick_lat>=35.6745457) | (df.pick_lng<=68.1113787) | (df.pick_lng>=97.395561) | (df.drop_lat<=6.2325274) | (df.drop_lat>=35.6745457) | (df.drop_lng<=68.1113787) | (df.drop_lng>=97.395561)]

,index,ts,number,pick_lat,pick_lng,drop_lat,drop_lng,hour,mins,day,month,year,dayofweek,booking_timestamp,shift_booking_ts,booking_time_diff_hr,booking_time_diff_min,geodesic_distance
4266,742031,2020-06-22 07:19:06,80,12.926255,77.616400,0.000000e+00,0.000000e+00,7,19,22,6,2020,0,1592810346,1590934080,521,31271,8674.57
13118,2502259,2020-10-16 21:52:28,297,12.958342,77.517876,3.890229e+00,-3.344596e+01,21,52,16,10,2020,4,1602885148,1602884658,0,8,12181.79
14555,4344697,2021-01-07 13:17:11,345,12.824208,77.684840,5.347187e+01,-1.021332e+02,13,17,7,1,2021,3,1610025431,1609843045,50,3039,12658.48
20669,8297478,2021-03-26 20:16:01,485,12.932975,77.536230,2.819774e+01,1.129942e+02,20,16,26,3,2021,4,1616789761,1616697903,25,1530,4043.95
26884,1786595,2020-09-09 09:36:43,641,12.896367,77.623800,0.000000e+00,0.000000e+00,9,36,9,9,2020,2,1599644203,0,444345,26660736,8675.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3664741,1985134,2020-09-21 14:40:51,98929,12.852040,77.675490,1.400000e-45,1.400000e-45,14,40,21,9,2020,0,1600699251,1600355752,95,5724,8680.58
3670580,834555,2020-07-02 08:40:16,99078,12.924925,77.606125,3.772864e+01,-8.920558e+01,8,40,2,7,2020,3,1593679216,1591804249,520,31249,14231.82
3671696,2331458,2020-10-06 18:12:35,99104,12.928082,77.603350,1.376042e+01,1.004980e+02,18,12,6,10,2020,1,1602007955,1601834214,48,2895,2481.04
3681558,2747830,2020-11-02 18:57:02,99379,12.984081,77.593330,0.000000e+00,0.000000e+00,18,57,2,11,2020,0,1604343422,1604309746,9,561,8672.37
3701398,5191270,2021-02-01 18:32:03,99852,12.966105,77.598270,0.000000e+00,0.000000e+00,18,32,1,2,2021,0,1612204323,1612203705,0,10,8672.81

### OLA Bikes is only operational in India
### Removing all rides for which pickup or drop is outside INDIA.
#### Number of such cases: 642

In [27]:
df.reset_index(inplace = True, drop = True)
outside_India = df[(df.pick_lat<=6.2325274) | (df.pick_lat>=35.6745457) | (df.pick_lng<=68.1113787) | (df.pick_lng>=97.395561) | (df.drop_lat<=6.2325274) | (df.drop_lat>=35.6745457) | (df.drop_lng<=68.1113787) | (df.drop_lng>=97.395561)]
df = df[~df.index.isin(outside_India.index)].reset_index(drop = True)

In [28]:
df

,index,ts,number,pick_lat,pick_lng,drop_lat,drop_lng,hour,mins,day,month,year,dayofweek,booking_timestamp,shift_booking_ts,booking_time_diff_hr,booking_time_diff_min,geodesic_distance
0,2374378,2020-10-10 07:34:16,-1,12.975773,77.571070,12.878468,77.445330,7,34,10,10,2020,5,1602315256,0,445087,26705254,17.38
1,2405894,2020-10-11 08:23:42,-1,12.930813,77.609530,12.960320,77.587210,8,23,11,10,2020,6,1602404622,1602315256,24,1489,4.06
2,2406076,2020-10-11 11:57:17,-1,12.960213,77.587460,12.930824,77.609610,11,57,11,10,2020,6,1602417437,1602404636,3,213,4.04
3,2500477,2020-10-16 17:51:07,-1,12.924353,77.549410,12.932216,77.581825,17,51,16,10,2020,4,1602870667,1602417451,125,7553,3.62
4,2694503,2020-10-30 09:00:44,-1,12.945731,77.622500,12.973030,77.616840,9,0,30,10,2020,4,1604048444,1602870685,327,19629,3.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3708830,5768115,2021-02-12 19:37:11,99999,13.029848,77.593400,13.063751,77.589850,19,37,12,2,2021,4,1613158631,1613068718,24,1498,3.77
3708831,6102760,2021-02-19 20:43:25,99999,13.029296,77.592580,12.927923,77.627106,20,43,19,2,2021,4,1613767405,1613158631,169,10146,11.82
3708832,6137206,2021-02-20 17:34:45,99999,12.907576,77.600685,12.925874,77.607620,17,34,20,2,2021,5,1613842485,1613767405,20,1251,2.16
3708833,6555089,2021-02-27 08:26:23,99999,12.956665,77.521870,12.948099,77.562990,8,26,27,2,2021,5,1614414383,1613842485,158,9531,4.56
3708834,6888302,2021-03-04 19:13:13,99999,12.987954,77.555880,13.065613,77.559910,19,13,4,3,2021,3,1614885193,1614414383,130,7846,8.60

In [29]:
print("Number of Good Ride Requests: {}".format(len(df)))

Number of Good Ride Requests: 3708835

In [30]:
## How many pickups and drops are outside bangalore?
pck_outside_bng = df[(df.pick_lat<=12.8340125) | (df.pick_lat>=13.1436649) | (df.pick_lng<=77.4601025) | (df.pick_lng>=77.7840515)]
drp_outside_bng = df[(df.drop_lat<=12.8340125) | (df.drop_lat>=13.1436649) | (df.drop_lng<=77.4601025) | (df.drop_lng>=77.7840515)]
print("Number of Pickup Requests Outside Bangalore: ",len(pck_outside_bng))
print("Number of Customers pickup outside Bangalore: ",len(np.unique(pck_outside_bng['number'].values)))

print("Number of Drops Requests Outside Bangalore: ",len(drp_outside_bng))
print("Number of Customers Drop outside Bangalore: ",len(np.unique(drp_outside_bng['number'].values)))

Number of Pickup Requests Outside Bangalore:  155908
Number of Customers pickup outside Bangalore:  20473
Number of Drops Requests Outside Bangalore:  167338
Number of Customers Drop outside Bangalore:  26878

In [31]:
### Bounding PickUp Lat-Long Within State Karnataka
# ['11.5945587', '18.4767308', '74.0543908', '78.588083']
pck_outside_KA = df[(df.pick_lat<=11.5945587) | (df.pick_lat>=18.4767308) | (df.pick_lng<=74.0543908) | (df.pick_lng>=78.588083)]
drp_outside_KA = df[(df.drop_lat<=11.5945587) | (df.drop_lat>=18.4767308) | (df.drop_lng<=74.0543908) | (df.drop_lng>=78.588083)]
print("Pickups Outisde KA: {} \nDrop outside KA: {}".format(len(pck_outside_KA),len(drp_outside_KA)))
print("Number of Customers Drop outside KA: ",len(np.unique(drp_outside_KA['number'].values)))
print("Number of Customers pickup outside KA: ",len(np.unique(pck_outside_KA['number'].values)))

Pickups Outisde KA: 38807
Drop outside KA: 39585
Number of Customers Drop outside KA:  6917
Number of Customers pickup outside KA:  6302

In [32]:
total_ride_outside_KA = df[(df.pick_lat<=11.5945587) | (df.pick_lat>=18.4767308) | (df.pick_lng<=74.0543908) | (df.pick_lng>=78.588083) | (df.drop_lat<=11.5945587) | (df.drop_lat>=18.4767308) | (df.drop_lng<=74.0543908) | (df.drop_lng>=78.588083)]

In [33]:
print("Total Ride Outside Karnataka: {}".format(len(total_ride_outside_KA)))

Total Ride Outside Karnataka: 39632

### Total Ride Outside Karnataka: 39632
### OLA Bikes doesnot provide intercity requests. Considering these as system error requests

Source: https://www.olacabs.com/

In [34]:
## Rides for which geodesic distance > 500kms
## Pickup and drop not of KA (state where we have maximum booking requests and user base)
suspected_bad_rides = total_ride_outside_KA[total_ride_outside_KA.geodesic_distance > 500]
suspected_bad_rides

,index,ts,number,pick_lat,pick_lng,drop_lat,drop_lng,hour,mins,day,month,year,dayofweek,booking_timestamp,shift_booking_ts,booking_time_diff_hr,booking_time_diff_min,geodesic_distance
105,4765341,2021-01-21 23:18:35,0,12.958837,77.644485,21.149794,82.782000,23,18,21,1,2021,3,1611271115,1611219970,14,852,1058.39
7368,1756248,2020-09-08 14:49:08,154,12.922410,77.568270,25.549080,84.655800,14,49,8,9,2020,1,1599576548,1599496883,22,1327,1583.00
38148,586293,2020-06-04 18:13:54,878,12.970724,77.582420,21.504763,80.115160,18,13,4,6,2020,3,1591294434,1591266878,7,459,982.06
40544,122197,2020-04-07 11:09:24,913,13.004375,77.555210,19.075983,72.877655,11,9,7,4,2020,1,1586257764,1586102620,43,2585,837.66
40560,288777,2020-04-29 23:11:41,913,13.013597,77.545740,22.837053,69.724560,23,11,29,4,2020,2,1588201901,1588159989,11,698,1366.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3681746,770076,2020-06-25 11:32:12,99395,13.037086,77.515854,28.979435,77.689580,11,32,25,6,2020,3,1593084732,1593016475,18,1137,1765.26
3681747,1086664,2020-07-29 15:29:45,99395,12.975827,77.605644,28.979435,77.689580,15,29,29,7,2020,2,1596036585,1593084811,819,49196,1771.97
3685647,4377242,2021-01-09 14:10:14,99499,12.959066,77.656815,28.479555,77.079950,14,10,9,1,2021,5,1610201414,1610187082,3,238,1719.44
3685648,4377307,2021-01-09 14:57:02,99499,12.959036,77.656770,28.479555,77.079950,14,57,9,1,2021,5,1610204222,1610201414,0,46,1719.45
3699364,723201,2020-06-20 15:09:58,99817,12.973216,77.717860,27.299267,75.956764,15,9,20,6,2020,5,1592665798,1589621290,845,50741,1596.61

### There are 506 rides which are >500kms geodesic distance and are pickup & drop outside KA, these are suspected rides.

In [35]:
df = df[~df.index.isin(suspected_bad_rides.index)].reset_index(drop = True)

In [36]:
print("Number of Good Ride Requests: {}".format(len(df)))

Number of Good Ride Requests: 3708329

In [37]:
dataset = df[['ts', 'number', 'pick_lat','pick_lng','drop_lat','drop_lng','geodesic_distance','hour','mins','day','month','year','dayofweek','booking_timestamp','booking_time_diff_hr', 'booking_time_diff_min']]

In [38]:
dataset.to_csv('./../Data/clean_data.csv',index = False, compression = 'gzip')

## Some Stats: Of 1year of Ride Requests Data at OLA Bikes
### Ride request of same user with same timestamp: 113540
### None user_id: 116
### Number of requests to same pickup lat-long by a user within 1hour: 39,79,554
### Number of rides by a user within 8mins of booking to different pickup lat-long: 611891
### Number of Rides Requests less than 50meters of pickup and drop: 14460
### Number of Rides pickup or drop lat-long outside India: 642

### Our majority ride state is Karnataka
#### Total Ride Outside Karnataka (pickup or drop): 39632

### Rides which are outside KA and pickup to drop distance is >500kms: 506

## Number of Good Ride Requests: 3708329